name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: "5e98ca40-b2e9-4cc3-b5b0-35a79187668e"
          heroku_app_name: "uwa-test-27"
          heroku_email: "hasan@ictlabs.com.au"
